---
services:
  node:
    tty: true
    build: .
    image: ${IMAGE}:${TAG}
    env_file: [.env]

  # ensure that after using node tools init-db that we change the db host to "db" since it will
  # be accessed within the docker network
  db:
    image: postgres
    restart: always
    environment:
      # must match credentials and configuration used with nodetools
      POSTGRES_PASSWORD: postfiat
      POSTGRES_USER: postfiat
      POSTGRES_DB: postfiat_nft_db_testnet
    ports: [8543:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
